platform :ios, '9.0'
use_frameworks!

target 'APIJpushSwift' do
  
  pod 'Alamofire'

  # Pods for APIJpushSwift

  target 'APIJpushSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APIJpushSwiftUITests' do
    # Pods for testing
  end

end
